package com.company.piCalculators.equations;

import com.company.piCalculators.PiCalculator;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.*;

/**
 * Created by JoaoPaulo on 23-Apr-17.
 */
public class GregoryLeibnizEquationTest {

	PiCalculator piCalculator;

	@Before
	public void setUp() throws Exception {
		piCalculator = new PiCalculator();
		piCalculator.setAlgorithm(new GregoryLeibnizEquation());
	}

	@After
	public void tearDown() throws Exception {
		piCalculator = null;
	}

	@Test
	public void generatePi() throws Exception {
		piCalculator.setIterations(10000000L);
		BigDecimal pi = piCalculator.calculate();

		//The pi generated by this test of Gregory's equation isn't very accurate, it needs more iterations.
		BigDecimal previouslyCalculatedPi = new BigDecimal("3.1415924535897934032291742734600142883394369164307136088609695434570312500000");
		assertTrue(pi.equals(previouslyCalculatedPi));
	}

}