package com.company.piCalculators.equations;

import com.company.piCalculators.PiCalculator;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.math.BigDecimal;

import static org.junit.Assert.*;

/**
 * Created by JoaoPaulo on 23-Apr-17.
 */
public class NilakanthaSomayajiTest {

	PiCalculator piCalculator;

	@Before
	public void setUp() throws Exception {
		piCalculator = new PiCalculator();
		piCalculator.setAlgorithm(new NilakanthaSomayaji());
	}

	@After
	public void tearDown() throws Exception {
		piCalculator = null;
	}

	@Test
	public void generatePi() throws Exception {
		piCalculator.setIterations(10000000L);
		BigDecimal pi = piCalculator.calculate();

		//The pi generated by this test of Nilakantha's equation isn't very accurate, it needs more iterations.
		BigDecimal previouslyCalculatedPi = new BigDecimal("3.14159265358035337828434942991603679114793722296049908745248569704835756195848706084916557301767170429229736328125");
		assertTrue(pi.equals(previouslyCalculatedPi));
	}

}